cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_view, name='cart_view'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

madame_musette/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler500, handler403, handler405


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('user_profile/', include('django.contrib.auth.urls')),
    path('user_profile/', include('user_profile.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'madame_musette.views.handler404'
handler500 = 'madame_musette.views.handler500'
handler403 = 'madame_musette.views.handler403'
handler405 = 'madame_musette.views.handler405'

products/urls.py
from django.urls import path
from . import views
from .forms import CustomiseForm


urlpatterns = [
    path('', views.all_products, name='products'),    
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('customise/', views.CustomiseFormPreview(CustomiseForm),
         name='customise'),
    path('search/', views.search, name='search'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
    path('like', views.like_product, name='like'),  
    path('product/<int:pk>/add-review', views.add_review, name='add_review'),
    path('product/<int:pk>/delete-review', views.delete_review, name='delete_review')

]

orders/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField

from products.models import Product, Customise
from user_profile.models import UserProfile

# Copied form BoutiqueAdo and adopted for MadameMusette

# Orders models.


class Order(models.Model):

    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='purchases')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    address_line_1 = models.CharField(max_length=80, null=False, blank=False)
    address_line_2 = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a order item is added,
        accounting for delivery costs.
        """
        self.order_total = self.orderitems.aggregate(Sum('orderitem_total'))['orderitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='orderitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    customised = models.ManyToManyField(Customise, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    orderitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                          null=False, blank=False,
                                          editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.orderitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'ID {self.product.id} on order {self.order.order_number}'

products/forms.py
from django import forms
from django.contrib.auth.models import User
from .widgets import CustomClearableFileInput
from .models import Product, Category, Customise, Review
from user_profile.models import UserProfile
from django.forms import ModelChoiceField

# PRODUCT FORM (Copied from BoutiqueAdo)


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


# CUSTOMISE FORM


class ProductModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return "Product #%s %s / %s" % (obj.id, obj.name, obj.category)


class CustomiseForm(forms.ModelForm):
    product = ProductModelChoiceField(queryset=Product.objects.all())

    class Meta:
        model = Customise
        exclude = ('created_date',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field

        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'user_name': 'Username',
            'email': 'Email',
            'phone_number': 'Phone_number',
            'product': 'Choose Product',
            'sole': 'Choose Sole',
            'color': 'Chose Color',
            'logo': '',
            'special_size': 'Choose Size',
            'details': 'Write here some specific requirements.'
        }

        self.fields['product'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != ['sole', 'color', 'special_size', 'product']:
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]}'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'border-black \
                rounded-0 profile-form-input'


# REVIEW FORM 


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('body', 'rating', )

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'body': 'Write your review here.',
        }

        self.fields['body'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'rating':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'
            self.fields[field].label = False

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from formtools.preview import FormPreview
from .models import Product, Category, Customise, Review
from .forms import ProductForm, CustomiseForm, ReviewForm
from django.db.models.functions import Lower
from datetime import datetime
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Avg


AUTO_ID = 'formtools_%s'

# ALL PRODUCTS VIEW.


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    categories = None
    sort = None
    direction = None
    logged_user = request.user

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
                if sortkey == 'category':
                    sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories,
                                       in_stock=True)
            categories = Category.objects.filter(name__in=categories)

    page_num = request.GET.get('page', 1)
    paginator = Paginator(products, 16)
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    sorting_products = f'{sort}_{direction}'

    context = {
        'products': page_obj,
        'categories': categories,
        'sorting_products': sorting_products,
        'logged_user': logged_user,
       
    }
    return render(request, 'products/products.html', context)


# PRODUCT DETAILS VIEW


def product_detail(request, product_id):
    """ A view to show individual product details """
    product = get_object_or_404(Product, pk=product_id)

    num_review = Review.objects.filter(product=product).count()
    avg_review = Review.objects.filter(product=product).aggregate(average=Avg('rating'))

    context = {
        'product': product,
        'num_review': num_review,
        'avg_review': avg_review,
        }

    return render(request, 'products/product_detail.html', context)

# REVIEW PRODUCT VIEW


def add_review(request, pk):
    product = Product.objects.get(id=pk)
    form = ReviewForm(instance=product)   

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=product)
       
        if form.is_valid():
            name = request.user.username
            body = form.cleaned_data['body']
            rating = form.cleaned_data['rating']
            review = Review(product=product, author=name, body=body, rating=rating, date_created=datetime.now(), status=True)
            product_id = review.product.id            
            review.save()
            messages.success(request, 'Your review was submited')
            return redirect(reverse('product_detail', args=[product_id]))
        else:
            messages.error(request, 'form is invalid') 
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }

    return render(request, 'products/add_review.html', context)       

# DELETE REVIEW VIEW


def delete_review(request, pk):
    review = Review.objects.filter(product=pk).last()
    product_id = review.product.id
    review.delete()
    return redirect(reverse('product_detail', args=[product_id]))


# PRODUCT CUSTOMISE VIEW


class CustomiseFormPreview(FormPreview):
    form_template = 'products/customise.html'
    preview_template = 'products/preview.html'

    def done(self, request, cleaned_data):
        Customise.objects.create(**cleaned_data)
        messages.success(request, 'Your Request was succesfuly registred, and \
                on short time we will contact you by email.')
        return redirect(reverse('home'))


# ADD PRODUCT VIEW (Product manager function copied from BoutiqueAdo)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please\
                 ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)

# EDIT PRODUCT VIEW


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure \
                                     the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)

# DELETE PRODUCT VIEW

@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

#  SEARCH VIEW


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            query = Q(name__icontains=keyword) | Q(description__icontains=keyword)
            products = Product.objects.order_by('-updated_date').filter(query)
            product_count = products.count()

    data = {
        'keyword': keyword,
        'products': products,
        'product_count': product_count,
        }
    return render(request, 'products/products.html', data)

# LIKE PRODUCT VIEW


def like_product(request):
    product_id = request.POST.get('product_id')
    product = get_object_or_404(Product, id=product_id)
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
    else:
        product.like.add(request.user)
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base_shop.html" %}
{% load static %}
{% block extra_title %}Add Product{% endblock %}

<!-- Copied from BoutiqueAdo -->

{% block content %} 

    <div class="container add_product h-100">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn btn-outline-dark discover-btn w-25 float-right" id="cancel-add" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn btn-outline-dark discover-btn w-25 mr-5" id="add-prod" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/add_review.html
{% extends "base_shop.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block extra_title %}Add Review{% endblock %}

<!-- Copied from BoutiqueAdo -->

{% block content %} 

    <div class="container add_product h-100">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Add review</h2>
                
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="" class="form mb-2">
                    {% csrf_token %}
                    
                            {{ form | crispy }}
                       
                    <div class="text-right">
                        <a class="btn btn btn-outline-dark discover-btn w-25 float-right" id="cancel-add" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn btn-outline-dark discover-btn w-25 mr-5" type="submit">Add Review</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base_shop.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extra_title %}{{product.name}} Details{% endblock %}
{% block page_header %}

{% endblock %}

{% block content %}

<div class="container-fluid h-100 prod_detail_wrap">

    <div class="row">
        <!--Product image-->
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2 text-center">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}"
                        style=" height: 35rem; width: auto;">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}"
                        style=" height: 35rem; width: auto;">
                </a>
                {% endif %}
            </div>
            <div class="row">
                <div class="designer_name mt-8 ml-10 pl-3 float-left">
                    Designed by: <a href="{% url 'about' %}#card-group-designers"
                        class="link-offset-3-hover"><strong>{{ product.designer_id.first_name }}
                            {{ product.designer_id.last_name }}</strong></a>

                </div>
                <hr class="mb-5"> <br>

                <div class="mt-8 float-left">

                    {% if user.is_authenticated %}
                    <a href="{% url 'customise' %}" class="link-offset-3-hover "><strong class="mx-5">For Customised
                            Product CLICK
                            here.</strong></a>
                    {% else %}
                    <p>For <strong> Customise Product</strong> you need to
                        <a class=" mr-1 ml-1 text-orange" href="{% url 'account_signup' %}"> Sign-Up </a>
                        <span> or </span>
                        <a class="mr-1 ml-1 text-orange" href="{% url 'account_login' %}"> Log-In </a>
                    </p>
                    {% endif %}
                </div>

            </div>

        </div>
        <!--Product Details-->
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-5">
                <p class="mb-0 mt-5"> {{ product.name }}
                    {% if product.category %}
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        / <span>{{ product.category.friendly_name }}</span>
                    </a>
                </p>
                {% endif %}
                <p class="lead mb-0 text-left font-weight-bold mb-3 mt-3 ml-3">€ {{ product.price }}</p>
                <div class="row">                    
                    {% if product.rating %}
                    <small class="text-muted"><i class="fas fa-star mr-1 ml-3"></i>{{ avg_review.average|floatformat:1 }} / 5 ({{num_review}}) <span class="pl-3"> Write a <a href="#review"> review</a></span></small>
                    {% else %}
                    <small class="text-muted">No Rating</small>
                    {% endif %}
                </div>
                <div class="row">
                    {% if request.user.is_superuser %}
                    <small class="mt-3  ml-3">
                        <a href="{% url 'edit_product' product.id %}">Edit</a> |

                        <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                    </small>
                    {% endif %}
                </div>
                <p class="mt-3">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="row">

                            <div class="col-12">
                                <p><strong>Size:</strong></p>
                                <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                    <option value="uk4">UK 4</option>
                                    <option value="uk4.5">UK 4.5</option>
                                    <option value="uk5">UK 5</option>
                                    <option value="uk5.5">UK 5.5</option>
                                    <option value="uk6">UK 6</option>
                                    <option value="uk6.5">UK 6.5</option>
                                    <option value="uk7">UK 7</option>
                                    <option value="uk7.5">UK 7.5</option>
                                    <option value="uk8">UK 8</option>
                                    <option value="uk8.5">UK 8.5</option>
                                </select>

                                {% endif %}


                            </div>

                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group quantity-group">
                                    <div class="input-group">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <button class="decrement-qty btn btn-increment rounded-0"
                                                    data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-minus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                            <input class="form-control qty_input" type="number" name="quantity"
                                                value="1" min="1" max="99" data-item_id="{{ product.id }}"
                                                id="id_qty_{{ product.id }}">
                                            <div class="input-group-append">
                                                <button class="increment-qty btn btn-increment rounded-0"
                                                    data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fas fa-plus"></i>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col{% if s %}-12 mt-2{% endif %}">
                                    <input type="submit"
                                        class="btn btn-outline-dark btn-lg discover-btn text-uppercase mt-5"
                                        value="Add to Cart">
                                    <a href="{% url 'products' %}"
                                        class="btn btn-outline-dark btn-lg discover-btn  mt-5">

                                        <span class="text-uppercase ">Keep Shopping</span>
                                    </a>

                                </div>
                                <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="col-12 mt-5 mb-5">

    <h5 class="mt-5" id="review"><strong>Reviews and Ratings</strong></h5>
    <hr>
    <div class="row">
        <div class="col-sm">
            Reviews ({{num_review}})
            <div class="card example-1 scrollbar-ripe-malinka mr-8">
                <div class="card-body">
                    {%  if not product.reviews.all %}
                    <p>No reviews added yet...</p>
                    {% else %}
                    <div class="row">
                        {%  for review in product.reviews.all %}
                        <div class="col-sm">
                            <div class="row mt-5">
                                <div class="col-sm-4">
                                    <h6> Reviewed by: <strong>{{review.author}}</strong></h6>
                                </div>
                                <div class="col-sm">
                                    <span style="color:#9b5412;">{{ review.rating }} <i class="fa-solid fa-star"
                                            style="color:#9b5412;"></i></span>
                                </div>
                            </div>
                            <div>
                                <p><strong>Review: </strong>
                                    {{ review.body }}</p>
                                <p><small>{{ review.date_created}}</small></p>
                            </div>
                        </div>

                        <hr class="w-100">
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        <div class="col-sm">
            {% if user.is_authenticated %}
                <p><a class="btn btn btn-outline-dark discover-btn w-25 mr-5 mb-5"
                        href="{% url 'add_review' product.id %}">Add
                        Review</a></p>


                <p><a class="btn btn btn-outline-dark discover-btn w-25 mr-5"
                        href="{% url 'delete_review' product.id %}">Delete
                        Review</a></p>
            {% else %}                
                <p>For <strong> Review the Product</strong> you need to
                    <a class=" mr-1 ml-1 text-orange" href="{% url 'account_signup' %}"> Sign-Up </a>
                    <span> or </span>
                    <a class="mr-1 ml-1 text-orange" href="{% url 'account_login' %}"> Log-In </a>
                </p>
            {% endif %}   

        </div>
    </div>
</div>





<!-- End Product Details-->
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}

{% endblock %}